uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes

- .github/workflows/dev-metrics.yml
- gh_metrics_config.json
Configuration of the scripts that reads the metrics for the evaluation of the milestones
> API TASKS QUERIES

- src/userObject.js
User object added, please let me know if there's anything to add/improve before merging!
> User Object created

- backend/package-lock.json
- backend/package.json
- backend/src/handlers/UsersHandler.js
- backend/src/models/UserModel.js
> Generate Clients UUID and store it in the db

- backend/src/controllers/RoomsController.js
- backend/src/models/RoomsModel.js
Room creation backend logic. It will be further developed to work alongside the Lobby. For now its a blueprint of the logic.
> Rooms backend logic

- backend/src/gamestatus/GameStatus.js
- backend/src/gamestatus/GameStatus.test.js
Synced my local main branch and made a new local branch in order to pass over the progress I had made on the score calculations into something that would be easier to merge with main.
> Transitioned and finished Score System over with a new synced main branch

- backend/src/gamestatus/GameStatus.js
- frontend/src/gamestate/experimentalGame.js
Finalized pick up and put down mouse interaction functions for the GameStatus and integrated them into the experimental game test.
> Integrated Mouse Interactions (Domino Click | Table Click)

- backend/src/gamestatus/GameStatus.js
- frontend/src/gamestate/experimentalGame.js
Removed the lines causing issues on Main
> Patched out Issue #51

- backend/package.json
- backend/src/index.js
- frontend/src/Auth/Login.js
- frontend/src/Auth/config.js
- package.json
This adds the missing functionality for proper authentication in our login forms, it also adds CORS to the backend service as it is required for the request between the frontend and backend to work iirc. Was tested locally and works correctly.
Screenshots:
1. Login:
2. Sign Up:
**Successfully Created the user in the database.**
> Integration of Login form with backend service

- frontend/src/gamestate/Bot.js
- frontend/src/gamestate/experimentalGame.js
- frontend/src/gamestate/intermediateBot.js
Created a new Intermediate Bot that inherits from the Simple Domino Bot #151 . The difference from both bots is that this bot looks for the highes playable tile from their hand, and uses that tile.
> Creation of the IntermediateBot

- frontend/src/gamestate/table.js
The Table class currently has comments in Spanish, while other parts of the code are in English. This task is simply to translate the comments in the Table class so that it follows the structure of the other classes.
> Translate Table Class Comments

- .gitignore
- frontend/package.json
- frontend/src/Auth/Login.test.js
---
Added Unit Testing for Login.js file. Has a 100% coverage of all the code added.
> Login.js Unit Testing

- backend/package-lock.json
- backend/src/controllers/UsersController.js
- backend/src/handlers/UsersHandler.js
Error handling implemented for password missmatch at login and existing username/email at sign up. This will take care of task #135.
> Error handling implemented 

- frontend/src/gamestate/AchievementManager.test.js
> Unit test for achivementManager

- frontend/src/gamestate/experimentalGame.js
- frontend/src/lobby/lobby.js
- Added alert for when player clicks on lobby button to let them know they will lose progress. They can click it again and they will exit to lobby.
- Going from lobby to game is now fixed (default to classic rule).
> Fixed bug when going from lobby to game and added alert when going from game to lobby (player will lose progress).

- frontend/src/Auth/Login.css
- frontend/src/Auth/Login.js
- frontend/src/Auth/__test__/Login.test.js
- frontend/src/Auth/services/AuthService.js
- frontend/src/Auth/services/IAuthService.js
- frontend/src/Auth/styles/Login.css
[LTT] Integrated the **solid principles** covered in class coursework to the login component. Made use of these to improve the maintainability of the code and readability. Also integrated the new UI that follows the styling used by the homepage.
S - Single-responsibility Principle
O - Open-closed Principle
L - Liskov Substitution Principle
I - Interface Segregation Principle
D - Dependency Inversion Principle
Covers tasks:
- Closes #173 
- Closes #232
> Solid Principles on Login components. Updated UI [173,232]

- frontend/src/App.test.js
- frontend/src/gamestate/RuleEngine.js
- frontend/src/gamestate/experimentalGame.js
- frontend/src/lobby/lobby.js
**Intermediate Bot tests:**
- Best domino is chosen based on the score of domino (sum of tails)
- No valid domino.
- Consecutively choose the best next domino.
**Rule Engine tests:**
- No valid move when tails of given domino do not match those of the corners of the table.
- Valid move when the table is empty.
- Valid move when at least a tail of the given domino matches those of the corners of the table. 
** When writing tests for rule engine found out it was only validating the move based on left tail of given domino to left tail of free corner and right tail of given domino to right tail of free corner (should check left tail of given domino to both free corners). Changed `validateMove` to check for both.
> 153 - Added further testing for intermediate bot and rule engine. Fixed bug on rule engine.

- frontend/src/lobby/lobby.css
Here I was able to successfully  modify the lobby fonts and colors to match the defined retro pixel art color palette and apply a readable pixel font. Ensure these elements are consistently applied across all lobby components to maintain a cohesive look and feel that aligns with the game's visual style​.
> Applied visual design to the lobby consistent with the game's color palette

- frontend/src/Home/Home.css
Finished issue #225 
The home page's elements shrink and adjusts to the size of the window of the screen.
> Fixed the shrinking and stretching problem.

- backend/package-lock.json
- backend/src/controllers/UsersController.js
- backend/src/database/MongoDbConnection.js
- backend/src/di/container.js
- backend/src/index.js
- backend/src/routes/authRoutes.js
- backend/src/routes/healthzRoutes.js
- backend/src/routes/index.js
- backend/src/routes/userRoutes.js
Refactored the main `backend/src/index.js` to only contain code that belongs to the configuration of the service, preventing unrelated changes and decoupling from other components and responsibilities. These changes support the following SOLID principles:
* Single responsibility - Each module (routing, middleware, handlers, controllers) has a single, well-defined responsibility.
* Open Closed - Adding new routes or features only involves adding new files, without the need to modify existing ones.
* Dependency Inversion - Controllers don’t create or depend directly on handlers; they rely on abstractions, allowing easy swapping of dependencies.
TODO: Add examples in documentation, under "Fragments of Implementation"
> Refactored start up to leverage SOLID principles.

- gh_metrics_config.json
Fix version, milestone dates, and milestone names.
> Fix actions metrics

- backend/package-lock.json
- backend/package.json
- backend/src/handlers/__test__/UserHandler.test.js
Added unit testing for backend user Handling, installed testing dependencies for mocking classes and db functions.
> Backend Unit Test for User Handler

- frontend/src/Home/Home.css
- frontend/src/Home/Home.js
Here I was able to complete the modifications to the components of the home page so that it matches the other parts of the game. I used the same colors and changed the font family of all the text to 'Press Start 2P', sans-serif
> Completed the modifications

- frontend/src/lobby/lobby.css
- frontend/src/lobby/lobby.js
**Changes:**
1. Fixed text alignment issues across all screens.
2. Adjusted font sizes to ensure readability and visual balance.
3. Refined the color palette for consistency and better contrast.
4.	Updated the Selection Screen (Solo or Multiplayer).
5.	Improved the Solo Screen (Bot settings) with better alignment and font adjustments.
6.	Enhanced the Multiplayer Screen (Configure Room).
> Enhanced Lobby Screens

- frontend/src/gamestate/ruleEngine.md
added more documentation on the code on ruleEngine.md
> added documentation to the Rule engine md

- frontend/src/gamestate/Bots.md
Added a markdown documentation file to the bot classes (advanced bot  and domino bot) for the multiplayer dominoes project.
> created markdown documentation for the bot classes.

- frontend/src/App.test.js
- frontend/src/gamestate/RuleEngine.js
Added unit test for drawDominoes game mode, imitated the way it is being used in experimentalGame.
`domino_win_score` method was calculating the score based on 7 dominoes but this is not always the case, changed it to run the amount of dominoes in the player's hand.
> Added unit tests for drawDominoes game mode.

- backend/package-lock.json
- backend/package.json
- backend/src/controllers/UsersController.js
- backend/src/handlers/UsersHandler.js
- backend/src/index.js
- backend/src/middleware/authenticateJWT.js
Fixed the current JWT usage to increment its security, not allowing it to be hardcoded, and also decremented the time it stays active for it to be more secure.
> Incremented JWT security and fixed functionality

- frontend/src/App.js
- frontend/src/Home/ContactUs.js
- frontend/src/Home/FAQS.js
- frontend/src/Home/Home.js
- frontend/src/Home/PrivacyPolicy.js
This merge request introduces three new informational pages for our Domino game website: Contact Us, Privacy Policy, and FAQs. These pages provide players with easy access to essential information, improving the overall user experience and ensuring transparency.
1. Contact Us:
- 	Provides users with contact information, including support email, phone number, and office hours.
- 	Helps players reach out for assistance or provide feedback.
2. Privacy Policy:
- 	Outlines how user data is collected, used, and protected on our platform.
- 	Ensures compliance with data privacy standards and builds trust with players.
3. FAQs:
- 	Answers common questions about gameplay, rules, and account setup.
- 	Helps users quickly find answers, reducing potential support inquiries.
> Added Contact Us, FAQs, and Privacy Policy pages with routing.

- frontend/src/gamestate/experimentalGame.md
Added a markdown documentation file to experimental game for the multiplayer dominoes project.
> created markdown documentation for experimental game

- backend/package-lock.json
- backend/package.json
- backend/src/handlers/UsersHandler.js
- backend/src/models/UserModel.js
- backend/src/routes/authRoutes.js
Expanded the error handling for the User Handler and added an admin role to the user model which is by default set to user in the case we may want to add more permissions to different users. Also added a limit to the password and login attempts to ensure that users cant keep attempting to reset their password in an attempt to avoid brute force attacks
> Add more error handling for the mismatch JWT secret keys and added a Admin role to the User model and modify the timeout timers

- frontend/src/gamestate/experimentalGame.js
- frontend/src/gamestate/table.js
Fixed the issue where dominoes placed on the table were not in the correct orientation, ensuring the numbers match with their neighbors. Additionally, added functionality for dominoes placed vertically to rotate 90 degrees and align with their neighbors, making the game more realistic.
> Improving Domino Visuals and Orientation

- frontend/src/gamestate/Chat.md
Created a markdown documentation file for chat popup in Multiplayer Dominoes that explains the class.
Closes #381
> Created markdown documentation for chat popup in Multiplayer dominoes.

- frontend/src/gamestate/table.md
Created markdown documentation for the table class in multiplayer dominoes that also explains how the dominoes class works.
Closes #380
> Created markdown document for table class.

- frontend/src/Home/Home.css
- frontend/src/Home/Home.js
Clicking on the "Instructions" header and the "Click here for more in-depth instructions" link now renders the rules and instructions page which can be seen in GameState. This pull request now adds more functionality to the home page and makes the Multi Dominoes project a more complete product.
> Render rules and instructions when clicking on "Instruction" links in the Home Page

- frontend/src/Home/ContactUs.js
- frontend/src/Home/FAQS.js
- frontend/src/Home/Home.css
- frontend/src/Home/PrivacyPolicy.js
This pull request adds a “Back To Home” button to the Contact Us page, providing users with an easy way to navigate back to the Home page. The button is styled to match the site’s theme.
> Add “Back To Home” Button to Contact Us Page

- frontend/src/App.css
- frontend/src/gamestate/experimentalGame.js
Re-designed the look and functionality of the lobby button in game state.
Previous button functionality:
New button functionality:
> Re-design lobby button functionality and look

- backend/src/controllers/RoomsController.js
- backend/src/controllers/UsersController.js
- backend/src/specifications/RoomSpecification.js
- backend/src/specifications/UserSpecification.js
I added specification patterns required for a Lecture Topic Task, the main task is a documentation one but I had to implement them first, here's what I plan on adding to the documentation, let me know if everything's good to go!
In our application, specification patterns have been applied to improve the validation processes for user and room management.
In the UsersController, specifications like EmailAvailableSpecification and UsernameAvailableSpecification are used to validate whether a user's email and username do not already exist before allowing account creation. This approach both ensures clear solving of concerns and also makes these rules reusable across other parts of the application where similar validations might be needed.
Similarly, the RoomsController has specifications such …
> Specification patterns added

- frontend/src/gamestate/AchievementManager.md
Added a md file for achivements
> added a md file for achivements

- backend/src/controllers/AchievementController.js
- backend/src/controllers/MatchController.js
- backend/src/controllers/RoomsController.js
- backend/src/di/container.js
- backend/src/handlers/AchievementHandler.js
- backend/src/handlers/MatchHandler.js
- backend/src/models/AchievementModel.js
- backend/src/models/MatchHistoryModel.js
- backend/src/models/UserAchievementModel.js
- backend/src/models/UserModel.js
- backend/src/repositories/AchievementRepository.js
- backend/src/repositories/MatchHistoryRepository.js
- backend/src/repositories/MatchRepository.js
- backend/src/repositories/RoomRepository.js
- backend/src/repositories/UserAchivementRepository.js
- backend/src/repositories/UserRepository.js
- backend/src/routes/achievementRoutes.js
- backend/src/routes/index.js
- backend/src/routes/matchRoutes.js
Based on the database schema design in #148, this contains the implementation of all the other tables. Including routes, controllers, handlers, repositories, models and endpoint registration.
All endpoints and changes were tested.
> Database schema implementation
